name: Deploy React App to Oracle Server

on:
  push:
    branches:
      - main   # main 브랜치에 push할 때 배포

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Clean old build folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -rf /var/www/build
            sudo mkdir -p /var/www/build
            sudo chown -R $USER:$USER /var/www/build
            sudo chmod -R 755 /var/www/build

      - name: Deploy to Oracle server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/*"
          target: "/var/www/build"
          strip_components: 1

      - name: Set proper permissions for nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/build
            sudo chmod -R 755 /var/www/build
            sudo find /var/www/build -type f -exec chmod 644 {} \;
